import { FileText, Download, CheckCircle2, AlertTriangle, Clock, DollarSign, Scale } from "lucide-react";
import { Button } from "@/components/ui/button";
import { jsPDF } from "jspdf";
import type { DetectedClause } from "./ClauseDetector";

interface TransparencyReportProps {
  score: number;
  clauseCount: number;
  criticalCount: number;
  highCount: number;
  contractLength: number;
  clauses: DetectedClause[];
}

const TransparencyReport = ({ score, clauseCount, criticalCount, highCount, contractLength, clauses }: TransparencyReportProps) => {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const timeStr = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });

  const metrics = [
    { icon: AlertTriangle, label: "Critical Issues", value: criticalCount.toString(), status: criticalCount === 0 ? "good" : "bad" },
    { icon: AlertTriangle, label: "High Risk Clauses", value: highCount.toString(), status: highCount <= 1 ? "warn" : "bad" },
    { icon: FileText, label: "Total Issues Found", value: clauseCount.toString(), status: clauseCount <= 2 ? "good" : "warn" },
    { icon: Scale, label: "Fairness Score", value: `${score}/100`, status: score >= 70 ? "good" : score >= 40 ? "warn" : "bad" },
    { icon: DollarSign, label: "Wage Competitiveness", value: score < 40 ? "Below Market" : "Market Rate", status: score < 40 ? "bad" : "good" },
    { icon: Clock, label: "Payment Timeline Risk", value: criticalCount > 0 ? "High" : "Moderate", status: criticalCount > 0 ? "bad" : "warn" },
  ];

  const statusColor = {
    good: "text-success",
    warn: "text-warning",
    bad: "text-destructive",
  };

  const statusBg = {
    good: "bg-success/10 border-success/20",
    warn: "bg-warning/10 border-warning/20",
    bad: "bg-destructive/10 border-destructive/20",
  };

  const handleDownload = () => {
    const doc = new jsPDF();

    // Config
    const margin = 15;
    let y = margin;
    const lineHeight = 7;

    // Helper to add text and increment Y
    const addText = (text: string, size = 12, isBold = false) => {
      doc.setFont("helvetica", isBold ? "bold" : "normal");
      doc.setFontSize(size);

      // Auto page break if needed
      if (y > 280) {
        doc.addPage();
        y = margin;
      }

      const lines = doc.splitTextToSize(text, 210 - margin * 2);
      doc.text(lines, margin, y);
      y += (lines.length * lineHeight) + (size === 12 ? 0 : 2);
    };

    // Header
    addText("GigAudit Transparency Report", 18, true);
    addText(`Generated: ${dateStr} at ${timeStr}`, 10);
    y += 5;
    doc.line(margin, y - 5, 210 - margin, y - 5);

    // Overall Status
    y += 5;
    addText(`OVERALL FAIRNESS SCORE: ${score}/100`, 14, true);
    addText(`Status: ${score >= 70 ? "FAIR" : score >= 40 ? "UNFAIR" : "PREDATORY"}`, 12, true);
    y += 5;

    // Issue Summary
    addText("ISSUE SUMMARY", 14, true);
    addText(`- Critical Issues: ${criticalCount}`);
    addText(`- High Risk Clauses: ${highCount}`);
    addText(`- Total Issues Found: ${clauseCount}`);
    addText(`- Contract Length: ${contractLength} characters`);
    y += 5;

    // Recommendation
    addText("RECOMMENDATION", 14, true);
    const recText = score < 40
      ? "This contract contains multiple exploitative clauses. We strongly recommend negotiating before signing."
      : score < 70
        ? "Several issues need attention before signing."
        : "Contract appears fair with minor areas for improvement.";
    addText(recText);

    // Detailed Clauses
    if (clauses && clauses.length > 0) {
      y += 10;
      doc.line(margin, y - 5, 210 - margin, y - 5);
      addText("DETAILED CLAUSE BREAKDOWN", 16, true);
      y += 5;

      clauses.forEach((clause, index) => {
        // Only print if it's an actual issue or if it's the only one
        if (clause.id === "0" && clauses.length > 1) return;

        addText(`${index + 1}. ${clause.title} [${clause.risk.toUpperCase()}]`, 12, true);

        y += 2;
        addText(`Category: ${clause.category}`, 10, true);
        addText(`Excerpt: "${clause.excerpt}"`, 10, false);
        y += 2;
        addText(`Why it's problematic:`, 10, true);
        addText(clause.explanation, 10, false);
        y += 2;
        addText(`Recommendation:`, 10, true);
        addText(clause.recommendation, 10, false);
        y += 8;
      });
    }

    // Footer
    y += 10;
    doc.line(margin, y - 5, 210 - margin, y - 5);
    addText("Generated by GigAudit AI Platform", 10, true);
    addText("gigaudit.ai", 10);

    doc.save("gigaudit-report.pdf");
  };

  return (
    <div className="rounded-2xl border border-border/60 bg-gradient-card p-6">
      <div className="flex items-start justify-between mb-6">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="w-2 h-2 rounded-full bg-success animate-pulse" />
            <span className="text-xs text-muted-foreground font-mono">REPORT GENERATED</span>
          </div>
          <h2 className="text-2xl font-bold" style={{ fontFamily: "Space Grotesk, sans-serif" }}>Transparency Report</h2>
          <p className="text-sm text-muted-foreground mt-1 font-mono">{dateStr} &bull; {timeStr}</p>
        </div>
        <Button onClick={handleDownload} variant="outline" className="border-border/60 gap-2 text-sm hover:border-primary/50 hover:bg-primary/5">
          <Download className="w-4 h-4" />
          Export PDF
        </Button>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mb-6">
        {metrics.map((m) => {
          const Icon = m.icon;
          return (
            <div key={m.label} className={`rounded-xl border p-3 ${statusBg[m.status as keyof typeof statusBg]}`}>
              <Icon className={`w-4 h-4 ${statusColor[m.status as keyof typeof statusColor]} mb-2`} />
              <div className={`text-lg font-bold font-mono ${statusColor[m.status as keyof typeof statusColor]}`}>{m.value}</div>
              <div className="text-xs text-muted-foreground mt-0.5">{m.label}</div>
            </div>
          );
        })}
      </div>

      {/* Summary */}
      <div className="p-4 rounded-xl bg-secondary/50 border border-border/40">
        <div className="flex items-start gap-3">
          <CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-semibold mb-1">AI Summary</p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              {score < 40
                ? `This contract scored ${score}/100 and contains ${criticalCount} critical and ${highCount} high-risk clauses. The payment delay, overbroad IP assignment, and one-sided arbitration terms are particularly concerning. Do not sign without renegotiation.`
                : score < 70
                  ? `This contract scored ${score}/100. While some terms are standard, ${clauseCount} issues require attention before signing. Review the negotiation playbook for evidence-based counteroffers.`
                  : `This contract scored ${score}/100 and appears generally fair. Minor improvements are possible but this contract meets most industry standards for gig workers.`
              }
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TransparencyReport;
